// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using RH.Models;
using System;

namespace RH.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20180107112216_iniciandoBanco")]
    partial class iniciandoBanco
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RH.Models.Candidato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Candidatos");
                });

            modelBuilder.Entity("RH.Models.CandidatoProcesso", b =>
                {
                    b.Property<int>("CandidatoId");

                    b.Property<int>("ProcessoId");

                    b.HasKey("CandidatoId", "ProcessoId");

                    b.HasIndex("ProcessoId");

                    b.ToTable("CandidatoProcesso");
                });

            modelBuilder.Entity("RH.Models.CandidatoTecnologia", b =>
                {
                    b.Property<int>("CandidatoId");

                    b.Property<int>("TecnologiaId");

                    b.HasKey("CandidatoId", "TecnologiaId");

                    b.HasIndex("TecnologiaId");

                    b.ToTable("CandidatoTecnologia");
                });

            modelBuilder.Entity("RH.Models.Processo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Processos");
                });

            modelBuilder.Entity("RH.Models.ProcessoTecnologia", b =>
                {
                    b.Property<int>("ProcessoId");

                    b.Property<int>("TecnologiaId");

                    b.Property<int>("Peso");

                    b.HasKey("ProcessoId", "TecnologiaId");

                    b.HasIndex("TecnologiaId");

                    b.ToTable("ProcessoTecnologia");
                });

            modelBuilder.Entity("RH.Models.Tecnologia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Tecnologias");
                });

            modelBuilder.Entity("RH.Models.CandidatoProcesso", b =>
                {
                    b.HasOne("RH.Models.Candidato", "Candidato")
                        .WithMany("ProcessosSeletivos")
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RH.Models.Processo", "Processo")
                        .WithMany("Candidatos")
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RH.Models.CandidatoTecnologia", b =>
                {
                    b.HasOne("RH.Models.Candidato", "Candidato")
                        .WithMany("Tecnologias")
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RH.Models.Tecnologia", "Tecnologia")
                        .WithMany("Candidatos")
                        .HasForeignKey("TecnologiaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RH.Models.ProcessoTecnologia", b =>
                {
                    b.HasOne("RH.Models.Processo", "Processo")
                        .WithMany("Tecnologias")
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RH.Models.Tecnologia", "Tecnologia")
                        .WithMany("Processos")
                        .HasForeignKey("TecnologiaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
